server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: local
  #session:
  #  store-type: redis
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-idle: 10
        max-wait: 2000
jwt.key: 7Iqk7ZSE66eBIOu2gO2KuCDqs7XrtoDtlZjsnpAh
